# Generated by Django 4.2.16 on 2025-02-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_share', models.DateTimeField(auto_now_add=True)),
                ('ispublisht', models.BooleanField(default=True)),
            ],
        ),
    ]
